title: Coord2Region Config Builder
description: Interactive configuration builder and landing page for Coord2Region Phase 2.
baseurl: ""
url: ""
markdown: kramdown
permalink: pretty
include:
  - assets/js
  - assets/css
exclude:
  - node_modules
  - package-lock.json
  - yarn.lock
  - pnpm-lock.yaml
  - website
  - vite.config.ts
  - tsconfig.json
  - playwright.config.ts
  - tests
plugins: []
