name: Website

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install 'pydantic>=2.6.0'

      - name: Generate JSON schema
        run: python scripts/generate_schema.py

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: web-interface/package-lock.json

      - name: Install web dependencies
        run: npm ci
        working-directory: web-interface

      - name: Build web assets
        run: npm run build
        working-directory: web-interface

      - name: Generate test preview shell
        run: npm run generate:test-page
        working-directory: web-interface

      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: web-interface

      - name: Run Playwright UI checks
        run: npm run test:ui
        working-directory: web-interface

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          working-directory: web-interface

      - name: Build Jekyll site
        working-directory: web-interface
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: web-interface/_site

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
